name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit and tag
        id: vars
        run: |
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          target: production
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cis-bel-front:latest
          build-args: |
            SOURCE_COMMIT=${{ steps.vars.outputs.commit }}
            SOURCE_TAG=${{ steps.vars.outputs.tag }}

      - name: Notify Telegram
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"${{ secrets.TG_CHAT_ID }}"'",
              "parse_mode": "Markdown",
              "text": "‚úÖ *Docker –æ–±—Ä–∞–∑—ã —É—Å–ø–µ—à–Ω–æ –æ–ø—É–±–ª–∏–∫–æ–≤–∞–Ω—ã!*\n\nüì¶ –û–±—Ä–∞–∑—ã:\n- `${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-fpm:latest`\n- `${{ secrets.DOCKERHUB_USERNAME }}/bel-dle-nginx:latest`\n\nüßë –ö–æ–º–º–∏—Ç: `${{ steps.vars.outputs.commit }}`\nüè∑Ô∏è –¢–µ–≥: `${{ steps.vars.outputs.tag }}`",
              "reply_markup": {
                "inline_keyboard": [[
                  {
                    "text": "üîç –û—Ç–∫—Ä—ã—Ç—å GitHub Actions",
                    "url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
                  }
                ]]
              }
            }'

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"${{ secrets.TG_CHAT_ID }}"'",
              "parse_mode": "Markdown",
              "text": "‚ùå *–û—à–∏–±–∫–∞ –≤ GitHub Actions Workflow!*\n\nüßë –ê–≤—Ç–æ—Ä: ${{ github.actor }}\nüìù Commit: `${{ github.sha }}`",
              "reply_markup": {
                "inline_keyboard": [[
                  {
                    "text": "üìÑ –û—Ç–∫—Ä—ã—Ç—å –ª–æ–≥",
                    "url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
                  }
                ]]
              }
            }'